FROM niaquinto/gradle

MAINTAINER Juan Salas "juan.salas.santillana@ucsp.edu.pe"

LABEL description="A base container for gradle applications"

COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
